"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { isOrderIdShape } from "@/lib/orders/read-buyer-orders";
const MAX_NOTE_LENGTH=500;
export type AdminReturnActionResult={ok:true;requestId:string;status:string}|{ok:false;code:"UNAUTHENTICATED"|"VALIDATION_FAILED"|"FORBIDDEN"|"REQUEST_NOT_FOUND"|"INVALID_TRANSITION"|"NOT_WIRED"|"DB_ERROR";message:string};
const notWired=():AdminReturnActionResult=>({ok:false,code:"NOT_WIRED",message:"Return management is not connected yet. The atomic admin database migration has not been applied, so nothing was changed."});
function rpcError(e:{code?:string;message?:string}|null):AdminReturnActionResult { const m=e?.message??""; if(e?.code==="PGRST202"||e?.code==="42883"||/function .* does not exist/i.test(m))return notWired(); if(/SKXNZ_UNAUTHENTICATED/.test(m))return{ok:false,code:"UNAUTHENTICATED",message:"Please sign in."}; if(/SKXNZ_ADMIN_REQUIRED/.test(m))return{ok:false,code:"FORBIDDEN",message:"Only administrators can update return status."}; if(/SKXNZ_RETURN_NOT_FOUND/.test(m))return{ok:false,code:"REQUEST_NOT_FOUND",message:"That return request could not be found."}; if(/SKXNZ_INVALID_TRANSITION/.test(m))return{ok:false,code:"INVALID_TRANSITION",message:"That return transition is not allowed. Refund and pickup states require real provider flows."}; if(/SKXNZ_NOTE_TOO_LONG/.test(m))return{ok:false,code:"VALIDATION_FAILED",message:`Notes must be ${MAX_NOTE_LENGTH} characters or fewer.`}; return{ok:false,code:"DB_ERROR",message:"The return status could not be updated right now."}; }
export async function adminUpdateReturnStatus(input:{requestId:string;nextStatus:string;note?:string|null}):Promise<AdminReturnActionResult>{ if(!input||!isOrderIdShape(input.requestId)||typeof input.nextStatus!=="string")return{ok:false,code:"REQUEST_NOT_FOUND",message:"That return request could not be found."}; const note=typeof input.note==="string"?input.note.trim():"";if(note.length>MAX_NOTE_LENGTH)return{ok:false,code:"VALIDATION_FAILED",message:`Notes must be ${MAX_NOTE_LENGTH} characters or fewer.`};const db=await createClient();const{data:{user},error:userError}=await db.auth.getUser();if(userError||!user)return{ok:false,code:"UNAUTHENTICATED",message:"Please sign in."};const{data:role,error:roleError}=await db.from("users").select("role").eq("id",user.id).maybeSingle();if(roleError)return{ok:false,code:"DB_ERROR",message:"The return status could not be updated right now."};if(role?.role!=="ADMIN")return{ok:false,code:"FORBIDDEN",message:"Only administrators can update return status."};const{data,error}=await db.rpc("admin_update_return_status_atomic",{p_request_id:input.requestId,p_next_status:input.nextStatus,p_note:note||null});if(error)return rpcError(error);const row=Array.isArray(data)?data[0]:data;if(!row||typeof row.request_id!=="string"||typeof row.status!=="string")return{ok:false,code:"DB_ERROR",message:"The return status could not be updated right now."};revalidatePath("/admin/returns");revalidatePath(`/admin/returns/${row.request_id}`);return{ok:true,requestId:row.request_id,status:row.status};}
