export {
  classifySkxnzAssistantRequest,
  createSkxnzAssistantResponse,
  extractQueryIntent,
  findProductsForPrompt,
  getAIStyledProducts,
  getLimitedEditionProducts,
  getNewSeasonProducts,
  recommendByStyle,
  recommendSimilarProducts,
  skxnzAssistantLimits,
  type SkxnzAssistantContext,
  type SkxnzAssistantIntent,
  type SkxnzAssistantProductRecommendation,
  type SkxnzAssistantResponse,
  type SkxnzAssistantSuggestedLink,
} from "@/src/lib/skxnzAssistant";
